"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const questao3_1 = require("./questao3");
const produto1 = new questao3_1.Produto(123, 50, "Camiseta");
const produto2 = new questao3_1.Produto(456, 100, "Calça Jeans");
const produto3 = new questao3_1.Produto(789, 200, "Tênis");
const item1 = new questao3_1.ItemPedido(produto1, 2);
const item2 = new questao3_1.ItemPedido(produto2, 1);
const item3 = new questao3_1.ItemPedido(produto3, 3);
const pedido = new questao3_1.Pedido();
pedido.adicionar_item(item1);
pedido.adicionar_item(item2);
pedido.adicionar_item(item3);
const total_pedido = pedido.obter_total();
console.log(`Total do pedido: R$${total_pedido.toFixed(2)}`);
